#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m' # No Color

main() {

    INSTALL_DIR="$(brew --prefix 2>/dev/null || echo /usr/local)/bin"

    echo "Uninstalling noddy from ${INSTALL_DIR}..."
    rm -f "${INSTALL_DIR}/noddy"
    rm -rf "${INSTALL_DIR}/toyland"
    echo "${GREEN}noddy has been uninstalled\n${NC}"

}

main
