#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m' # No Color

main() {

    INSTALL_DIR="$(brew --prefix 2>/dev/null || echo /usr/local)/bin"

    BREW_PREFIX="$(brew --prefix 2>/dev/null || echo /usr/local)"

    echo "Uninstalling noddy from ${INSTALL_DIR}..."
    rm -f "${INSTALL_DIR}/noddy"
    rm -rf "${INSTALL_DIR}/toyland"

    rm -f "${BREW_PREFIX}/share/zsh/site-functions/_noddy"
    rm -f "${BREW_PREFIX}/etc/bash_completion.d/noddy"
    rm -f "${BREW_PREFIX}/share/fish/vendor_completions.d/noddy.fish"
    echo "${GREEN}noddy has been uninstalled\n${NC}"

}

main
