#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m' # No Color

main() {

    echo "Upgrading noddy ..."

    WORKDIR="$(mktemp -d)"
    trap 'rm -rf "$WORKDIR"' EXIT

    git clone https://github.com/clouddrove/noddy.git --depth 1 "$WORKDIR/noddy" || exit 1
    sh "$WORKDIR/noddy/toyland/setup/install" || exit 1

    echo "${GREEN}noddy has been updated to the latest version\n${NC}"

}

main
